# Generated by Django 2.2.6 on 2019-10-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
